title: "> /dev/null 2>&1"
email: aj@48k.io
description: >
  48k, Dtrace, Hadoop, Mesos, Spark, Erlang, JVM, node.js, PHP, Python, porting software, Ansible, Puppet, Capistrano,
  Habitat, Poudriere, Packer, terraform, FreeBSD, illumos, OmniOS, Unix, scaling databases, AWS, Google Cloud,
  OpenStack, Rackspace, ZFS, bhyve KVM, Xen
baseurl: ""
url: "http://log.48k.io"
social_sites:
  twitter: x90T
  github: wakeful
google_analytics: "UA-87114721-2"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
